# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10_f-kh1hnISzHusKIwmy9uF2BORohsr4
"""



# --- BLOCK 1
import pandas as pd
import requests
import os
import time
from concurrent.futures import ThreadPoolExecutor
from google.colab import files
from tqdm.notebook import tqdm

# 1. CONFIGURATION
MAPBOX_TOKEN = "pk.eyJ1Ijoic2lkZGh1MTgiLCJhIjoiY21qd3p3bzI0M3l3YjNscXlobjNkazk0MCJ9.6ijiF-FLDxmDo6IUD0cpdA"
STYLE_ID = "mapbox/satellite-v9"
IMAGE_SIZE = "600x600"
ZOOM_LEVEL = 18
OUTPUT_DIR = "satellite_images"

# Performance Settings
MAX_WORKERS = 10  # Downloads 10 images at once
MAX_RETRIES = 3   # Tries 3 times if internet/API flickers

os.makedirs(OUTPUT_DIR, exist_ok=True)

# ---------------------------------------------------------
# CORE FUNCTION: Download with Retry & Tracking
# ---------------------------------------------------------
def download_image(lat, lon):
    filename = f"{lat}_{lon}.jpg"
    file_path = os.path.join(OUTPUT_DIR, filename)

    if os.path.exists(file_path):
        return "skipped"

    url = f"https://api.mapbox.com/styles/v1/{STYLE_ID}/static/{lon},{lat},{ZOOM_LEVEL},0,0/{IMAGE_SIZE}?access_token={MAPBOX_TOKEN}"

    for attempt in range(MAX_RETRIES):
        try:
            response = requests.get(url, timeout=15)
            if response.status_code == 200:
                with open(file_path, 'wb') as f:
                    f.write(response.content)
                return "success"
            elif response.status_code == 429: # Rate limit hit
                time.sleep(2)
        except Exception:
            time.sleep(1) # Wait before retrying

    return "failed"

# ---------------------------------------------------------
# PROCESSOR: Handles the File Upload & Multithreading
# ---------------------------------------------------------
def upload_and_process(label_name):
    print(f"\n{'='*60}\nSTEP: UPLOAD {label_name.upper()}\n{'='*60}")
    uploaded = files.upload()

    if not uploaded:
        print("No file selected.")
        return

    file_name = next(iter(uploaded))
    df = pd.read_excel(file_name)

    # Clean column names
    df.columns = [c.lower().strip() for c in df.columns]
    df.rename(columns={'latitude': 'lat', 'longitude': 'long'}, inplace=True)

    if 'lat' not in df.columns or 'long' not in df.columns:
        print(f"❌ ERROR: Could not find lat/long columns in {file_name}")
        return

    points = list(zip(df['lat'], df['long']))
    results = {"success": 0, "failed": 0, "skipped": 0}

    print(f"🚀 Starting fast download for {len(points)} locations...")

    # Parallel Execution with Progress Bar
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        # We wrap the executor in tqdm to show the visual bar
        list_results = list(tqdm(executor.map(lambda p: download_image(*p), points),
                                 total=len(points),
                                 desc=f"Downloading {label_name}"))

    # Tallies the results
    for r in list_results:
        results[r] += 1

    # Final Report for this file
    print(f"\n--- {label_name} Summary ---")
    print(f"✅ Successfully Downloaded: {results['success']}")
    print(f"⏭️  Already Existed (Skipped): {results['skipped']}")
    if results['failed'] > 0:
        print(f"❌ Failed Downloads: {results['failed']}")
    print("-" * 30)

# ---------------------------------------------------------
# RUN
# ---------------------------------------------------------
upload_and_process("TRAINING DATA")
upload_and_process("TEST DATA")

print("\n✨ ALL BLOCKS COMPLETE.")